name: repo-tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]


jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    name: Test docker builds
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build bionic
        run: ./build.sh 18.04 ./18.04

      - name: Test bionic
        run: |
          docker run --rm dr-yocto:18.04

      - name: Build focal
        run: ./build.sh 20.04 ./20.04

      - name: Test focal
        run: |
          docker run --rm dr-yocto:20.04

      - name: Check workdir
        run: ls -lt /
